[package]
name = "terminal-staking"
version = "0.1.0"
description = "Terminal NFT Staking Program using MPL Core"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "terminal_staking"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]

[dependencies]
anchor-lang = { version = "0.31.1", features = ["init-if-needed"] }
anchor-spl = "0.31.1"
mpl-core = "0.7.2"
